"""add_trigram_indexes

Revision ID: 61571c5661d5
Revises: 1f960d4b0e52
Create Date: 2026-06-30 17:20:26.727693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61571c5661d5'
down_revision: Union[str, Sequence[str], None] = '1f960d4b0e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index('ix_ticket_customer_email_trgm', 'tickets', ['customer_email'], unique=False, postgresql_using='gin', postgresql_ops={'customer_email': 'gin_trgm_ops'})
    op.create_index('ix_ticket_customer_name_trgm', 'tickets', ['customer_name'], unique=False, postgresql_using='gin', postgresql_ops={'customer_name': 'gin_trgm_ops'})
    op.create_index('ix_ticket_description_trgm', 'tickets', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_ticket_subject_trgm', 'tickets', ['subject'], unique=False, postgresql_using='gin', postgresql_ops={'subject': 'gin_trgm_ops'})
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_subject_trgm', table_name='tickets', postgresql_using='gin', postgresql_ops={'subject': 'gin_trgm_ops'})
    op.drop_index('ix_ticket_description_trgm', table_name='tickets', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_ticket_customer_name_trgm', table_name='tickets', postgresql_using='gin', postgresql_ops={'customer_name': 'gin_trgm_ops'})
    op.drop_index('ix_ticket_customer_email_trgm', table_name='tickets', postgresql_using='gin', postgresql_ops={'customer_email': 'gin_trgm_ops'})
    # ### end Alembic commands ###
